### ISSUE TITLE
Custom scripts for package.yml

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#111]
The manifest currently only provides `test_hook` key for hooking in. If the user wants to execute some scripts before execution, he needs to provide an additional file. I would be nice if he include the scripting inside the package.yml, similar to .gitlab-ci.yml:

```yaml
name: mySuite
before_run:
   - mkdir -p ./foo
after_run:
  - ./report-junit
```
