### ISSUE TITLE
Add VCS support for imports

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#45]
The bigger a test suite becomes, the more important test suite organization becomes. Current manifest file `package.yml` use file-system paths to refer to generated files, adapters and libraries. For example:
```yaml
name: example
imports:
  - $CMAKE_BINARY_DIR/generated/TestPorts/
  -  ...
```
This leaves the provisioning of dependencies to a third party build-system. This introduces additional complexity and causes a bad user experience.

Being able to specify URL inside the `package.yml` would allow ntt to use domain specific knowledge, like [Titan information files](https://gitlab.eclipse.org/eclipse/titan/titan.ProtocolModules.HTTP2/-/blob/master/HTTP2_CNL113851.tpd),  and download and cache test suite dependencies automatically. For example:

```yaml
name: example
imports:
  - https://gitlab.eclipse.org/eclipse/titan/titan.TestPorts.TCPasp
  - ...
```
