### ISSUE TITLE
Add `variables` section to manifest

### ISSUE THREAD

**Issue by 5nord** [nokia/ntt#59]
A `variables` section for `package.yml` file could help making manifest more readable.
Example:
```
variables:
    COMMON_DIR: "../../../libs"
    PLUGINS_DIR: "${K3ROOT}/lib/plugins"

imports:
   - ${COMMON_DIR}/foo
   - ${PLUGINS_DIR}/tcpPlugin

... 
```
